name: header-comments

on: [push]

jobs:
  test:
    name: Add comments
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Add comments to /
        uses: koj-co/header-comments
        with:
          directory: /
      
      - name: Add comments to /angleutilities/
        uses: koj-co/header-comments
        with:
          directory: /angleutilities

      - name: Add comments to /dialogs/
        uses: koj-co/header-comments
        with:
          directory: /dialogs

      - name: Add comments to /tables/
        uses: koj-co/header-comments
        with:
          directory: /tables
      
      - name: Create pull request with changes
        uses: peter-evans/create-pull-request@v3