name: header-comments

on: [push, pull_request]

jobs:
  test:
    name: Add comments
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Add comments to /src
        uses: koj-co/header-comments@v1.0.5
        with:
          directory: /src
      - name: Add comments to /src/angleutilities
        uses: koj-co/header-comments@v1.0.5
        with:
          directory: /src/angleutilities
      - name: Add comments to /src/dialogs
        uses: koj-co/header-comments@v1.0.5
        with:
          directory: /src/dialogs
      - name: Add comments to /src/tables
        uses: koj-co/header-comments@v1.0.5
        with:
          directory: /src/tables
      - name: Create pull request with changes
        uses: peter-evans/create-pull-request@v3