name: header-comments

on: [push, pull_request]

jobs:
  test:
    name: Add comments
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      #- name: Add comments to /
      #  uses: pabio/header-comments
      #  with:
      #    directory: /
      
      - name: Add comments to angleutilities
        uses: pabio/header-comments
        with:
          directory: angleutilities

      - name: Add comments to dialogs
        uses: pabio/header-comments
        with:
          directory: dialogs

      - name: Add comments to tables
        uses: pabio/header-comments
        with:
          directory: tables
      
      - name: Create pull request with changes
        uses: peter-evans/create-pull-request@v3